# permissions for end users to edit mindeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-bounded-deployment
    app.kubernetes.io/managed-by: kustomize
  name: mindeployment-editor-role
rules:
- apiGroups:
  - deploy.stonal.io
  resources:
  - mindeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.stonal.io
  resources:
  - mindeployments/status
  verbs:
  - get
