---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - deploy.stonal.io
  resources:
  - mindeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.stonal.io
  resources:
  - mindeployments/finalizers
  verbs:
  - update
- apiGroups:
  - deploy.stonal.io
  resources:
  - mindeployments/status
  verbs:
  - get
  - patch
  - update
