apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: tool-k8s-crd-mindeployment
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
