apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mindeployments.stonal.io
spec:
  group: stonal.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  description: Minimum number of replicas
                maxReplicas:
                  type: integer
                  description: Maximum number of replicas (optional)
                template:
                  type: object
                  description: Pod template to use for creating pods
  scope: Namespaced
  names:
    plural: mindeployments
    singular: mindeployment
    kind: MinDeployment
    shortNames:
      - md
