apiVersion: deploy.stonal.io/v1
kind: MinDeployment
metadata:
  name: nginx-mindeployment
spec:
  replicas: 3
  maxReplicas: 5  # Optional
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80

---
# Standard nginx deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app2
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
# MinDeployment based on the standard nginx deployment
apiVersion: deploy.stonal.io/v1
kind: MinDeployment
metadata:
  name: nginx-deployment-mindeployment
spec:
  sourceDeploymentName: nginx-deployment
  replicas: 2
  maxReplicas: 10
