# This workflow doesn't respect the stonal conventions as we intend to
# open-source this project.
name: Lint & Build

on:
  push:
jobs:
  lint-and-build:
    runs-on: stonal-ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.24.1'

    - name: Installing tools
      run: |
        sudo apt-get update && sudo apt-get install -y make

    - name: Linting
      uses: golangci/golangci-lint-action@v6.5.1
      with:
          # https://github.com/golangci/golangci-lint/releases
          version: v1.64.8
          args: -v --timeout=20m
          # skip-cache: true

    - name: Run golangci-lint
      run: golangci-lint run

    - name: Build project
      run: make build
