# This workflow doesn't respect the stonal conventions as we intend to
# open-source this project.
name: Lint & Build

on:
  push:
jobs:
  lint-and-build:
    runs-on: stonal-ubuntu-24.04
    steps:
    - uses: actions/checkout@v6.0.3

    - name: Set up Go
      uses: actions/setup-go@v6.4.0
      with:
        go-version: '1.26.4'

    - name: Installing tools
      run: |
        sudo apt-get update && sudo apt-get install -y make

    - name: Linting
      uses: golangci/golangci-lint-action@v9.2.1
      with:
          # https://github.com/golangci/golangci-lint/releases
          version: v2.11.4
          args: -v --timeout=20m
          # skip-cache: true

    - name: Run golangci-lint
      run: golangci-lint run

    - name: Build project
      run: make build
